config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: "homes#top"
  get "/home/about" => "homes#about", as: 'about'
  resources :books, only: [:new, :create, :index, :show, :edit, :update, :destroy]
  resources :users, only: [:index, :show, :edit, :update]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord

   belongs_to :user

   has_one_attached :profile_image

  validates :title, presence: true
  validates :body, presence: true, length: { maximum: 200 }

  def get_profile_image(width, height)
    unless profile_image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      profile_image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    profile_image.variant(resize_to_limit: [width, height]).processed
  end

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :books, dependent: :destroy

  has_one_attached :profile_image

  validates :name, uniqueness: true, length: { in: 2..20 }
  validates :introduction, length: { maximum: 50 }

  def get_profile_image(width, height)
    unless profile_image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      profile_image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    profile_image.variant(resize_to_limit: [width, height]).processed
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  before_action :configure_permitted_parameters, if: :devise_controller?

  def after_sign_in_path_for(resource)
    user_path(resource)
  end

  def after_sign_out_path_for(resource)
    root_path
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:email])
  end

end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :authenticate_user!
  before_action :correct_user, only: [:edit, :update]

  def new
    @book = Book.new
  end

  def create
    @book = Book.new(book_params)
    @user = current_user
    @book.user_id = current_user.id
    if @book.save
      flash[:notice] = "You have created book successfully."
      redirect_to book_path(@book.id)
    else
      @books = Book.all
      render("books/index")
    end
  end

  def index
    @user = current_user
    @users = User.all
    @book = Book.new
    @books = Book.all
  end

  def show
    @book = Book.find(params[:id])
    @user = @book.user
    @booknew = Book.new
  end

  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
     flash[:notice] = "You have updated book successfully."
     redirect_to book_path(@book.id)
    else
     @books = Book.all
     render("books/edit")
    end
  end

  def edit
    @book = Book.find(params[:id])
  end

  def destroy
    book = Book.find(params[:id])
    book.destroy
    redirect_to '/books'
  end

  private

  def book_params
    params.require(:book).permit(:title, :body)
  end

  def correct_user
    @book = Book.find(params[:id])
    @user = @book.user
    redirect_to(books_path) unless @user == current_user
  end

end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end

  def about
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  before_action :correct_user, only: [:edit, :update]

  def show
    @user = User.find(params[:id])
    @book = Book.new
    @books = @user.books
  end

  def index
    @user = current_user
    @users = User.all
    @book = Book.new
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      flash[:notice] = "You have updated user successfully."
     redirect_to user_path(@user.id)
    else
      @users = User.all
      render("users/edit")
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :profile_image, :introduction)
  end

  def correct_user
    @user = User.find(params[:id])
    redirect_to(user_path(current_user)) unless @user == current_user
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/_userinfo.html.erb
<h2>User info</h2>
    <p><%= image_tag user.get_profile_image(100,100) %></p>
    <table class="table">
    <tbody>
     <tr>
      <td>name</td>
      <td><%= user.name %></td>
     </tr>
     <tr>
      <td>introduction</td>
      <td><%= user.introduction %></td>
     </tr>
    </tbody>
   </table>


　　<div class="row">
 　　 <%= link_to edit_user_path(user.id) ,class: "btn btn-outline-secondary btn-block" do %>
  　　 <i class="fas fa-user-cog"></i>
 　　 <% end %>
　　</div>

app/views/books/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
  		<h1>Editing Book</h1>

    <% if @book.errors.any? %>
     <div id="error_explanation">
     <h3><%= @book.errors.count %>errors prohibited this book from being saved:</h3>
     <ul>
      <% @book.errors.full_messages.each do |message| %>
       <li><%= message %></li>
      <% end %>
     </ul>
     </div>
    <% end %>

  		<%= form_with model: @book do |f| %>
       <div class="form-group">
        <label>Title</label>
         <div class="field">
          <%= f.text_field :title, class: "form-control" %>
         </div>
       </div>

       <div class="form-group">
        <label>Opinion</label>
         <div class="field">
          <%= f.text_area :body, class: "form-control" %>
         </div>
       </div>

       <div class="form-group">
         <%= f.submit 'Update Book', class: "btn btn-success" %>
       </div>

      <% end %>

      <%= link_to "Show", book_path(@book.id) %>
      |
      <%= link_to "Back", '/books' %>

    </div>
  </div>
</div>

app/views/books/index.html.erb
<div class="container">

 <% if @book.errors.any? %>
  <div id="error_explanation">
   <h3><%= @book.errors.count %> errors prohibited this obj from being saved:</h3>
    <ul>
      <% @book.errors.full_messages.each do |message| %>
         <li><%= message %></li>
      <% end %>
    </ul>
  </div>
 <% end %>

 <div class="row">
  <div class="col-md-3">

  <%= render 'books/userinfo', user: @user %>

　<h2 class="mt-3">New book</h2>

  <%= form_with model: @book do |f| %>
   <div class="form-group">
    <label>Title</label>
     <div class="field">
     <%= f.text_field :title %>
     </div>
   </div>

   <div>
    <label>Opinion</label>
    <div class="field">
      <%= f.text_area :body %>
    </div>
   </div>

    <div class="form-group">
      <%= f.submit 'Create Book', class: "btn btn-success" %>
    </div>
   <% end %>
  </div>


  <div class="col-md-8 offset-md-1">
  <h2>Books</h2>
   <table class="table table-hover table-inverse">
    <thead>
     <tr>
      <th></th>
      <th>Title</th>
      <th>Opinion</th>
      <th></th>
    </tr>
    </thead>

    <tbody>
    <% @books.each do |f| %>
     <tr>
      <td>
       <%= link_to user_path(f.id) do %>
        <%= image_tag f.user.get_profile_image(80,80) %>
       <% end %>
      </td>
      <td>
       <%= link_to book_path(f.id) do %>
        <%= f.title %>
       <% end %>
      </td>
      <td><%= f.body %></td>
     </tr>
    <% end %>
    </tbody>
   </table>
  </div>
 </div>
</div>

app/views/books/new.html.erb
<h1>Books#new</h1>
<p>Find me in app/views/books/new.html.erb</p>

app/views/books/show.html.erb
<div class="container">
 <div class="row">
  <div class="col-md-3">

  <%= render 'books/userinfo', user: @user %>

  <h2 class="mt-3">New book</h2>

  <% if @book.errors.any? %>
   <div id="error_explanation">
    <h2><%= @book.errors.count %>errors prohibited this book from being saved:</h2>
    <ul>
      <% @book.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
   </div>
  <% end %>

  <%= form_with model: @booknew do |f| %>
   <div class="form-group">
    <label>Title</label>
     <div class="field">
      <%= f.text_field :title, class: "form-control" %>
     </div>
   </div>

   <div class="form-group">
    <label>Opinion</label>
     <div class="field">
      <%= f.text_area :body, class: "form-control" %>
     </div>
   </div>

   <div class="form-group">
    <%= f.submit 'Create Book', class: "btn btn-success" %>
   </div>
   <% end %>
  </div>

  <div class="col-md-8 offset-md-1">
  <h2>Book detail</h2>

   <table class="table table-hover table-inverse">
    <thead>
    </thead>

    <tbody>
     <tr>
      <td>
       <%= link_to user_path(@user.id) do %>
        <%=image_tag @user.get_profile_image(100,100) %>
        <p><%= @user.name %></p>
       <% end %>
      </td>
      <td>
        <%= link_to book_path(@book.id) do %>
        <p><%= @book.title %></p>
        <% end %>
      </td>
      <td><%= @book.body %></td>
      <td>
       <% if @user == current_user %>
        <%= link_to "Edit" ,edit_book_path(@book.id), class: "btn btn-sm btn-success" %>
       <% end %>
      </td>
      <td>
       <% if @user == current_user %>
         <%= link_to "Destroy", book_path(@book.id), method: :delete, class: "btn btn-sm btn-danger", "data-confirm" => "本当に消しますか？" %>
       <% end %>
      </td>
     </tr>
    </tbody>
   </table>
  </div>
 </div>
</div>

app/views/homes/about.html.erb
<p id="notice"></p>
<div class="container">
  <div class="row">
    <h1 class="px-3 mx-auto">Welcome to
      <i class="fas fa-book"></i>
      <strong>Bookers</strong>!
    </h1>
  </div>
</div>

app/views/homes/top.html.erb
<div class="container">
  <div class="row">
    <div class="mx-auto col-11 col-sm-10 col-lg-8 col-xl-6">
      <h1>welcome to
       <i class="fas fa-book"></i>
       <strong>Bookers</strong> !!
      </h1>

      <p>In
       <i class="fas fa-book"></i>
       <strong>Bookers</strong>,
      </p>

      <p>you can share and exchange  your opinions , inpressions , and emotions</p>

      <p> about various books!</p>
      <div class="btn-wrapper col-10 mx-auto">
        <div class="row">
          <%= link_to "Log in", new_user_session_path, class: "btn btn-info btn-sm btn-block mb-3 btn-#17a2b8" %>
        </div>
        <div class="row">
          <%= link_to "Sign up", new_user_registration_path, class: "btn btn-success btn-sm btn-block btn-#28a745" %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html class="d-flex flex-column">
  <head>
    <title>Bookers2</title>
    <meta name="viewport" content="width=device-width,initial-scale=1, maximum-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container">
          <a class="navbar-brand" href="/">
            <span>Bookers</span>
          </a>
          <butoon class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown"
                        aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </butoon>
          <div class="collapse navbar-collapse" id="navbarNavDropdown">
            <ul class="navbar-nav ml-auto">
            <% if user_signed_in? %>
            <li>
              <%= link_to user_path(current_user.id), class: 'nav-link text-light' do %>
              <i class="fas fa-home" style="color:#fff;"></i> Home
              <% end %>
            </li>
            <li>
              <%= link_to users_path, class: 'nav-link text-light' do %>
              <i class="fas fa-users" style="color:#fff;"></i> Users
              <% end %>
            </li>
            <li>
              <%= link_to  books_path, class: 'nav-link text-light' do %>
              <i class="fas fa-book-open" style="color:#fff;"></i> Books
              <% end %>
            </li>
            <li>
              <%= link_to destroy_user_session_path, method: :delete, class: 'nav-link text-light' do %>
              <i class="fas fa-sign-out-alt" style="color:#fff;"></i> Log out
              <% end %>
            </li>
            <% else %>
            <li>
              <%= link_to root_path, class: 'nav-link text-light' do %>
              <i class="fas fa-home" style="color:#fff;"></i> Home
              <% end %>
            </li>
            <li>
              <%= link_to about_path, class: 'nav-link text-light' do %>
              <i class="fas fa-link" style="color:#fff;"></i> About
              <% end %>
            </li>
            <li>
              <%= link_to new_user_registration_path, class: 'nav-link text-light' do %>
              <i class="fas fa-user-plus"  style="color:#fff;"></i> Sign up
              <% end %>
            </li>
            <li>
              <%= link_to new_user_session_path, class: 'nav-link text-light' do %>
              <i class="fas fa-sign-in-alt" style="color:#fff;"></i> Log in
              <% end %>
            </li>
           <% end %>
         </ul>
        </div>
      </div>
    </nav>
    </header>
    <main>
    <% flash.each do |message_type, message| %>
    <%= content_tag :div, message, class: message_type %>
    <% end %>
    <%= yield %>
    </main>
    <footer>
      <div class="container mt-5">
        <div class="row">
          <div class="mx-auto">
            <p>CopyRight Infratop.inc</p>
          </div>
        </div>
      </div>
    </footer>
  </body>
</html>

app/views/users/edit.html.erb
<p id="notice"></p>
  <div class="container">
    <div class="row">
      <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
        <h2>User info</h2>

        <% if @user.errors.any? %>
         <div id="error_explanation">
         <h3><%= @user.errors.count %> errors prohibited this obj from being saved:</h3>
         <ul>
           <% @user.errors.full_messages.each do |message| %>
            <li><%= message %></li>
           <% end %>
         </ul>
         </div>
        <% end %>

        <%= form_with model: @user do |f| %>
        <div class="form-group">
          <label for="inputName">Name</label>
           <div class="field">
            <%= f.text_field :name, class: "form-control", autofocus: true, id:"inputName" %>
           </div>
        </div>

        <div class="form-group">
         <label for="inputImage">Image</label>
          <div class="field">
           <%= f.file_field :profile_image, placeholder: "Image", accept: "image/*" %>
          </div>
        </div>

        <div class="form-group">
         <label for="inputIntroduction">Introduction</label>
          <div class="field">
           <%= f.text_area :introduction, class: "form-control", autofocus: true, id:"inputIntroduction" %>
          </div>
        </div>

        <div class="form-group">
         <%= f.submit "Update User", class: "btn btn-secondary" %>
        </div>

        <% end %>
      </div>
    </div>
 </div>

app/views/users/index.html.erb
<div class="container">
 <div class="row">
  <div class="col-md-3">

  <%= render 'books/userinfo', user: @user %>

  <h2 class="mt-3">New book</h2>

  <% if @book.errors.any? %>
    <div id="error_explanation">
     <h2><%= @book.errors.count %>errors prohibited this book from being saved %></h2>
      <ul>
       <% @book.errors.full_messages.each do |message| %>
       <li><%= message %></li>
       <% end %>
      </ul>
    </div>
  <% end %>

  <%= form_with model: @book do |f| %>
   <div class="form-group">
    <label>Title</label>
     <div class="field">
     <%= f.text_field :title, class: "form-control" %>
     </div>
   </div>

   <div class="form-group">
    <label>Opinion</label>
    <div class="field">
      <%= f.text_area :body %>
    </div>
   </div>

    <div class="form-group">
      <%= f.submit 'Create Book', class: "btn btn-success" %>
    </div>
   <% end %>
  </div>

  <div class="col-md-8 offset-md-1">
  <h2>Users</h2>
   <table class="table">
    <thead>
     <tr>
      <th>image</th>
      <th>name</th>
      <th></th>
    </tr>
    </thead>

    <tbody>
    <% @users.each do |f| %>
     <tr>
      <td><%= image_tag f.get_profile_image(80,80) %></td>
      <td><%= f.name %></td>
      <td><%= link_to "Show", user_path(f.id) %></td>
     </tr>
    <% end %>
    </tbody>
   </table>
  </div>
 </div>
</div>

app/views/users/show.html.erb
<div class="container">
 <div class="row">
  <div class="col-md-3">

   <%= render 'books/userinfo', user: @user %>

   <h2 class="mt-3">New book</h2>

   <% if @book.errors.any? %>
    <div id="error_explanation">
     <h2><%= @book.errors.count %>errors prohibited this book from being saved %></h2>
      <ul>
       <% @book.errors.full_messages.each do |message| %>
         <li><%= message %></li>
       <% end %>
     </ul>
    </div>
   <% end %>

   <%= form_with model: @book do |f| %>
    <div class="form-group">
     <label>Title</label>
      <div class="field">
      <%= f.text_field :title %>
      </div>
    </div>

    <div>
     <label>Opinion</label>
     <div class="field">
       <%= f.text_area :body %>
     </div>
    </div>

    <div class="form-group">
      <%= f.submit 'Create Book', class: "btn btn-success" %>
    </div>
   <% end %>
  </div>


  <div class="col-md-8 offset-md-1">
  <h2>Books</h2>
   <table class="table table-hover table-inverse">
    <thead>
     <tr>
      <th></th>
      <th>Title</th>
      <th>Opinion</th>
      <th></th>
    </tr>
    </thead>

    <tbody>
    <% @books.each do |f| %>
     <tr>
      <td>
       <%= link_to user_path(@user) do %>
        <%=image_tag f.user.get_profile_image(80,80) %>
       <% end %>
      </td>
      <td>
       <%= link_to book_path(f.id) do %>
        <%= f.title %>
       <% end %>
      </td>
      <td><%= f.body %></td>
     </tr>
    <% end %>
    </tbody>
   </table>
  </div>
 </div>
</div>